
####################################################################
# ----  T G LEC-53     CONFIGMAP  ------------
####################################################################

# ConfigMap:- A ConfigMap is an API object used to store non-confidential data in key-value pairs. 
#             Pods can consume ConfigMaps as environment variables, command-line arguments, or as configuration files in a volume.
#             A ConfigMap allows you to decouple environment-specific configuration from your container images, 
#             so that your applications are easily portable.

#             we can define data(configuration) in a 'key value pair' or a 'file content' using ConfigMap.
#             we can refer ConfigMap key value pairs in a pod manifest environment vars.Or we can mount ConfigMap
#             file(data) as a volume to our pods.
#             ConfigMap in k8s will maintain data in a human readale format.

# secret:- A Secret is an object that contains a small amount of sensitive data such as a password, a token, or a key. 
#          Such information might otherwise be put in a Pod specification or in a container image.
#          Using a Secret means that you don't need to include confidential data in your application code.
# ************    CONFIGMAP   ***************************

#AS A VOLUME  -------

##  vi deployconfig.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: myvolconfig    # ---- NAME 0f cm
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
    volumeMounts:
      - name: testconfigmap   ####---- SAME
        mountPath: "/tmp/config"   # the config files will be mounted as ReadOnly by default here
  volumes:
  - name: testconfigmap     ####---- SAME
    configMap:    # ----- ''CONFIG MAP''   object
       name: mymap   # this should match the config map name created in the first step  ( sample.conf  )
       items:
       - key: sample.conf
         path: sample.conf
...         

#   AS A ENVIRONMENT VARIABLE --------

##  vi deployenv.yml

---
apiVersion: v1
kind: Pod

  name: myenvconfig
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
    env:
    - name: MYENV         # --- env name in which value of the key is stored
      valueFrom:
        configMapKeyRef:  # ---- refrence config map key 
          name: mymap      # name of the config created
          key: sample.conf # ----- take this file  and run on the container 





# ************************   SECRET ( for all secret  file to hide)*********************

##   vi deploysecret.yml               
---
apiVersion: v1
kind: Pod
metadata:
  name: myvolsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Technical-guftgu; sleep 5 ; done"]
    volumeMounts:
      - name: testsecret
        mountPath: "/tmp/mysecrets"   # the secret files will be mounted as ReadOnly by default here
  volumes:
  - name: testsecret   # ----create volume name is 'testsecret'
    secret:
       secretName: mysecret  # ----- take this file 
...     