# *****************    vi pod8.yml  - EXAMPLE OF REPLICATION CONTROLLER - *********************

---
kind: ReplicationController  # --------- kind of  " object "             
apiVersion: v1
metadata:
  name: rc-demo    # -------- name of Replication Controller  
spec:
  replicas: 3   # ---------------- desired no of PODS.    always 2 POD running             
  selector:       # ----- Rc support only ( equality based selectors )   
    team: dev  #$$$$  # must match ""labels""   jis pr ye ''labele'' lga ho us pod ko select krna hai..                          
  template:        # ---- template  defines to launch New PODS. { PODS INFO }
    metadata:                  
      name: rc-demo    
      labels:      # -------- selector value need to match labels  {RC support only '1 labels'}        
        team: dev  #$$$$ 
    spec:
     containers:
       - name: rc-demo1
         image: nginx:1.7.1
         ports: 
           - containerPort: 80
...           

#-------------------------------------------------------------------------------------------------------------=
---
kind: ReplicationController # ---------kind of  " object "             
apiVersion: v1
metadata:
  name: myreplica   # --------name of  Replication Controller  
spec:
  replicas: 2   # ----------------desired no of PODS.    always 2 POD running             
  selector:          
    myname: mylabel   #-- $$$$  # must match ""labels""   jis pr ye ''labele'' lga ho us pod ko select krna hai..                          
  template:        # ----template  defines to launch New PODS. {INSIDE -POD INFORMATIONS}
    metadata:                  
      name: testpodrc   
      labels:      # --------selector value need to match labels {FOR PODS}         
        apps: my-app  #-- $$$$ 
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-AAMIR; sleep 5 ; done"]
         ports:
           - containerPort: 8080
... 

---
kind: Service    #------ Defines to create Service type Object
apiVersion: v1
metadata:
  name: testpodsvc  # ----- service name
spec:
  type: NodePort   #--- Specifies the service type i.e ClusterIP or NodePort
  selector:
    apps: my-app #-- $$$$    #---- Apply this service to any pods which has the specific label
  ports:
    - port: 80        # Containers port exposed
      targetPort: 8080     # Pods port   
...

#-------------------------------------------------------------------------------------------------------------=



